# Generated by Django 3.2 on 2023-04-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficReport',
            fields=[
                ('traffic_report_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('published_date', models.DateTimeField()),
                ('issue_reported', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('traffic_report_status', models.CharField(max_length=100)),
                ('traffic_report_status_date_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'traffic_report',
                'managed': True,
            },
        ),
    ]
