# Generated by Django 3.2 on 2023-04-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficreport',
            name='traffic_report_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
