# Generated by Django 3.2 on 2023-04-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0002_alter_trafficreport_traffic_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficreport',
            name='traffic_report_id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
