# Generated by Django 3.2 on 2023-04-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0004_crash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animal_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
                ('datetime', models.DateTimeField()),
                ('found_location', models.CharField(max_length=256, null=True)),
                ('intake_type', models.CharField(max_length=256, null=True)),
                ('intake_condition', models.CharField(max_length=256, null=True)),
                ('animal_type', models.CharField(max_length=256, null=True)),
                ('sex_upon_intake', models.CharField(max_length=256, null=True)),
                ('age_upon_intake', models.CharField(max_length=256, null=True)),
                ('breed', models.CharField(max_length=256, null=True)),
                ('color', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'animal',
                'managed': True,
            },
        ),
    ]
