# Generated by Django 3.2 on 2023-04-20 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0005_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitAgency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_report_year', models.IntegerField(null=True)),
                ('ntd_id', models.PositiveIntegerField(null=True)),
                ('legacy_ntd_id', models.CharField(max_length=128, null=True)),
                ('agency_name', models.CharField(max_length=256, null=True)),
                ('agency_status', models.CharField(max_length=64, null=True)),
                ('reporter_type', models.CharField(max_length=64, null=True)),
                ('reporting_module', models.CharField(max_length=64, null=True)),
                ('city', models.CharField(max_length=64, null=True)),
                ('state', models.CharField(max_length=8, null=True)),
                ('census_year', models.IntegerField(null=True)),
                ('uza_name', models.CharField(max_length=64, null=True)),
                ('uza', models.IntegerField(null=True)),
                ('uza_area_sqm', models.IntegerField(null=True)),
                ('uza_population', models.BigIntegerField(null=True)),
                ('status_2021', models.CharField(max_length=64, null=True)),
            ],
            options={
                'db_table': 'transit_agency',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransitExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=8, null=True)),
                ('service', models.CharField(max_length=8, null=True)),
                ('status_mode', models.CharField(max_length=64, null=True)),
                ('year', models.IntegerField()),
                ('expense_type', models.CharField(max_length=64)),
                ('expense', models.BigIntegerField()),
                ('transit_agency_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='views.transitagency')),
            ],
            options={
                'db_table': 'transit_expense',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='transitagency',
            constraint=models.UniqueConstraint(fields=('ntd_id', 'legacy_ntd_id'), name='unique_registration'),
        ),
    ]
