# Generated by Django 3.2 on 2023-04-20 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0005_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionalRouteMiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=8, null=True)),
                ('service', models.CharField(max_length=8, null=True)),
                ('year', models.IntegerField()),
                ('drm', models.IntegerField()),
            ],
            options={
                'db_table': 'drm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=8, null=True)),
                ('service', models.CharField(max_length=8, null=True)),
                ('year', models.IntegerField()),
                ('fares', models.BigIntegerField()),
            ],
            options={
                'db_table': 'fares',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PassengerMilesTraveled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=8, null=True)),
                ('service', models.CharField(max_length=8, null=True)),
                ('year', models.IntegerField()),
                ('pmt', models.BigIntegerField()),
            ],
            options={
                'db_table': 'pmt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransitAgency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_report_year', models.IntegerField(null=True)),
                ('ntd_id', models.PositiveIntegerField(null=True)),
                ('legacy_ntd_id', models.CharField(max_length=128, null=True)),
                ('agency_name', models.CharField(max_length=256, null=True)),
                ('agency_status', models.CharField(max_length=64, null=True)),
                ('reporter_type', models.CharField(max_length=64, null=True)),
                ('reporting_module', models.CharField(max_length=64, null=True)),
                ('city', models.CharField(max_length=64, null=True)),
                ('state', models.CharField(max_length=8, null=True)),
                ('census_year', models.IntegerField(null=True)),
                ('uza_name', models.CharField(max_length=64, null=True)),
                ('uza', models.IntegerField(null=True)),
                ('uza_area_sqm', models.IntegerField(null=True)),
                ('uza_population', models.BigIntegerField(null=True)),
                ('status_2021', models.CharField(max_length=64, null=True)),
            ],
            options={
                'db_table': 'transit_agency',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VehiclesOperatedMaximumService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=8, null=True)),
                ('service', models.CharField(max_length=8, null=True)),
                ('year', models.IntegerField()),
                ('voms', models.IntegerField()),
                ('transit_agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='views.transitagency')),
            ],
            options={
                'db_table': 'voms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VehicleRevenueMiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=8, null=True)),
                ('service', models.CharField(max_length=8, null=True)),
                ('year', models.IntegerField()),
                ('vrm', models.BigIntegerField()),
                ('transit_agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='views.transitagency')),
            ],
            options={
                'db_table': 'vrm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VehicleRevenueHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=8, null=True)),
                ('service', models.CharField(max_length=8, null=True)),
                ('year', models.IntegerField()),
                ('vrh', models.BigIntegerField()),
                ('transit_agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='views.transitagency')),
            ],
            options={
                'db_table': 'vrh',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UnlinkedPassengerTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=8, null=True)),
                ('service', models.CharField(max_length=8, null=True)),
                ('year', models.IntegerField()),
                ('upt', models.BigIntegerField()),
                ('transit_agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='views.transitagency')),
            ],
            options={
                'db_table': 'upt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransitExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=8, null=True)),
                ('service', models.CharField(max_length=8, null=True)),
                ('year', models.IntegerField()),
                ('expense_type', models.CharField(max_length=64)),
                ('expense', models.BigIntegerField()),
                ('transit_agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='views.transitagency')),
            ],
            options={
                'db_table': 'transit_expense',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='transitagency',
            constraint=models.UniqueConstraint(fields=('ntd_id', 'legacy_ntd_id'), name='unique_registration'),
        ),
        migrations.AddField(
            model_name='passengermilestraveled',
            name='transit_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='views.transitagency'),
        ),
        migrations.AddField(
            model_name='fares',
            name='transit_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='views.transitagency'),
        ),
        migrations.AddField(
            model_name='directionalroutemiles',
            name='transit_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='views.transitagency'),
        ),
    ]
