# Generated by Django 3.2 on 2023-04-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0005_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_report_year', models.IntegerField(null=True)),
                ('ntd_id', models.PositiveIntegerField(null=True)),
                ('legacy_ntd_id', models.CharField(max_length=128, null=True)),
                ('agency_name', models.CharField(max_length=256, null=True)),
                ('agency_status', models.CharField(max_length=64, null=True)),
                ('reporter_type', models.CharField(max_length=64, null=True)),
                ('reporting_module', models.CharField(max_length=64, null=True)),
                ('city', models.CharField(max_length=64, null=True)),
                ('state', models.CharField(max_length=8, null=True)),
                ('census_year', models.IntegerField(null=True)),
                ('uza_name', models.CharField(max_length=64, null=True)),
                ('uza', models.IntegerField(null=True)),
                ('uza_area_sqm', models.IntegerField(null=True)),
                ('uza_population', models.BigIntegerField(null=True)),
                ('status_2021', models.CharField(max_length=64, null=True)),
                ('mode', models.CharField(max_length=8, null=True)),
                ('service', models.CharField(max_length=8, null=True)),
                ('status_mode', models.CharField(max_length=64, null=True)),
                ('year', models.IntegerField()),
                ('expense_type', models.CharField(max_length=64)),
                ('expense', models.BigIntegerField(default=0)),
            ],
        ),
    ]
