# Generated by Django 3.2 on 2023-04-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0006_transitexpense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transitexpense',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='transitexpense',
            name='expense',
            field=models.BigIntegerField(),
        ),
        migrations.AlterModelTable(
            name='transitexpense',
            table='transit_expense',
        ),
    ]
