# Generated by Django 3.2 on 2023-04-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0006_auto_20230420_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('budget', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'expense_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'mode',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'service',
                'managed': True,
            },
        ),
    ]
