# Generated by Django 3.2 on 2023-04-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0007_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('budget', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'expense_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'service',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='mode',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='mode',
            table='mode',
        ),
    ]
