# Generated by Django 3.2 on 2023-04-22 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0007_expensetype_mode_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionalroutemiles',
            name='mode',
            field=models.ForeignKey(default='MB', on_delete=django.db.models.deletion.DO_NOTHING, to='views.mode'),
        ),
        migrations.AlterField(
            model_name='directionalroutemiles',
            name='service',
            field=models.ForeignKey(default='DO', on_delete=django.db.models.deletion.DO_NOTHING, to='views.service'),
        ),
        migrations.AlterField(
            model_name='fares',
            name='mode',
            field=models.ForeignKey(default='MB', on_delete=django.db.models.deletion.DO_NOTHING, to='views.mode'),
        ),
        migrations.AlterField(
            model_name='fares',
            name='service',
            field=models.ForeignKey(default='DO', on_delete=django.db.models.deletion.DO_NOTHING, to='views.service'),
        ),
        migrations.AlterField(
            model_name='fares',
            name='transit_agency',
            field=models.ForeignKey(default='nan', on_delete=django.db.models.deletion.DO_NOTHING, to='views.transitagency'),
        ),
        migrations.AlterField(
            model_name='passengermilestraveled',
            name='mode',
            field=models.ForeignKey(default='MB', on_delete=django.db.models.deletion.DO_NOTHING, to='views.mode'),
        ),
        migrations.AlterField(
            model_name='passengermilestraveled',
            name='service',
            field=models.ForeignKey(default='DO', on_delete=django.db.models.deletion.DO_NOTHING, to='views.service'),
        ),
        migrations.AlterField(
            model_name='transitexpense',
            name='expense_type',
            field=models.ForeignKey(default='VO', on_delete=django.db.models.deletion.DO_NOTHING, to='views.expensetype'),
        ),
        migrations.AlterField(
            model_name='transitexpense',
            name='mode',
            field=models.ForeignKey(default='MB', on_delete=django.db.models.deletion.DO_NOTHING, to='views.mode'),
        ),
        migrations.AlterField(
            model_name='transitexpense',
            name='service',
            field=models.ForeignKey(default='DO', on_delete=django.db.models.deletion.DO_NOTHING, to='views.service'),
        ),
        migrations.AlterField(
            model_name='unlinkedpassengertrips',
            name='mode',
            field=models.ForeignKey(default='MB', on_delete=django.db.models.deletion.DO_NOTHING, to='views.mode'),
        ),
        migrations.AlterField(
            model_name='unlinkedpassengertrips',
            name='service',
            field=models.ForeignKey(default='DO', on_delete=django.db.models.deletion.DO_NOTHING, to='views.service'),
        ),
        migrations.AlterField(
            model_name='vehiclerevenuehours',
            name='mode',
            field=models.ForeignKey(default='MB', on_delete=django.db.models.deletion.DO_NOTHING, to='views.mode'),
        ),
        migrations.AlterField(
            model_name='vehiclerevenuehours',
            name='service',
            field=models.ForeignKey(default='DO', on_delete=django.db.models.deletion.DO_NOTHING, to='views.service'),
        ),
        migrations.AlterField(
            model_name='vehiclerevenuemiles',
            name='mode',
            field=models.ForeignKey(default='MB', on_delete=django.db.models.deletion.DO_NOTHING, to='views.mode'),
        ),
        migrations.AlterField(
            model_name='vehiclerevenuemiles',
            name='service',
            field=models.ForeignKey(default='DO', on_delete=django.db.models.deletion.DO_NOTHING, to='views.service'),
        ),
        migrations.AlterField(
            model_name='vehiclesoperatedmaximumservice',
            name='mode',
            field=models.ForeignKey(default='MB', on_delete=django.db.models.deletion.DO_NOTHING, to='views.mode'),
        ),
        migrations.AlterField(
            model_name='vehiclesoperatedmaximumservice',
            name='service',
            field=models.ForeignKey(default='DO', on_delete=django.db.models.deletion.DO_NOTHING, to='views.service'),
        ),
    ]
