# Generated by Django 3.2 on 2023-04-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0008_auto_20230422_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerPriceIndex',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('in_todays_dollars', models.FloatField(default=1)),
            ],
            options={
                'db_table': 'cpi',
                'managed': True,
            },
        ),
    ]
