# Generated by Django 3.2 on 2023-04-22 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0009_consumerpriceindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitexpense',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='views.consumerpriceindex'),
        ),
    ]
