# Generated by Django 3.2 on 2023-04-29 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0010_alter_transitexpense_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fares',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='views.consumerpriceindex'),
        ),
    ]
