# Generated by Django 3.2 on 2023-05-16 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0011_alter_fares_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyVehiclesOperatedMaximumService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('voms', models.IntegerField()),
                ('mode', models.ForeignKey(default='MB', on_delete=django.db.models.deletion.DO_NOTHING, to='views.mode')),
                ('service', models.ForeignKey(default='DO', on_delete=django.db.models.deletion.DO_NOTHING, to='views.service')),
                ('transit_agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='views.transitagency')),
            ],
            options={
                'db_table': 'monthly_voms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MonthlyVehicleRevenueMiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('vrm', models.BigIntegerField()),
                ('mode', models.ForeignKey(default='MB', on_delete=django.db.models.deletion.DO_NOTHING, to='views.mode')),
                ('service', models.ForeignKey(default='DO', on_delete=django.db.models.deletion.DO_NOTHING, to='views.service')),
                ('transit_agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='views.transitagency')),
            ],
            options={
                'db_table': 'monthly_vrm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MonthlyVehicleRevenueHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('vrh', models.BigIntegerField()),
                ('mode', models.ForeignKey(default='MB', on_delete=django.db.models.deletion.DO_NOTHING, to='views.mode')),
                ('service', models.ForeignKey(default='DO', on_delete=django.db.models.deletion.DO_NOTHING, to='views.service')),
                ('transit_agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='views.transitagency')),
            ],
            options={
                'db_table': 'monthly_vrh',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MonthlyUnlinkedPassengerTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('upt', models.BigIntegerField()),
                ('mode', models.ForeignKey(default='MB', on_delete=django.db.models.deletion.DO_NOTHING, to='views.mode')),
                ('service', models.ForeignKey(default='DO', on_delete=django.db.models.deletion.DO_NOTHING, to='views.service')),
                ('transit_agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='views.transitagency')),
            ],
            options={
                'db_table': 'monthly_upt',
                'managed': True,
            },
        ),
    ]
