# Generated by Django 4.1.5 on 2023-06-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("views", "0014_alter_routes_route_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trips",
            name="shape",
        ),
        migrations.AddField(
            model_name="trips",
            name="shape_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
