# Generated by Django 4.1.5 on 2023-07-17 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("views", "0015_remove_trips_shape_trips_shape_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutePerformance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("day_type", models.CharField(max_length=16)),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("date", models.DateTimeField()),
                ("average_daily_riders", models.FloatField(default=0)),
                ("number_days", models.PositiveSmallIntegerField(default=0)),
                ("revenue_hours", models.FloatField(default=0)),
                ("revenue_miles", models.FloatField(default=0)),
                ("total_hours", models.FloatField(default=0)),
                ("total_miles", models.FloatField(default=0)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="views.routes",
                    ),
                ),
            ],
            options={
                "db_table": "route_performance",
                "managed": True,
            },
        ),
    ]
