# Generated by Django 4.1.5 on 2024-01-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("views", "0016_routeperformance"),
    ]

    operations = [
        migrations.AddField(
            model_name="crash",
            name="micromobility_death_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crash",
            name="micromobility_fl",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="crash",
            name="micromobility_serious_injury_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
