# Generated by Django 4.2.16 on 2024-11-30 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("views", "0017_crash_micromobility_death_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendardates",
            name="transit_agency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="views.transitagency",
            ),
        ),
        migrations.AlterField(
            model_name="routes",
            name="transit_agency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="views.transitagency",
            ),
        ),
        migrations.AlterField(
            model_name="shapes",
            name="transit_agency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="views.transitagency",
            ),
        ),
        migrations.AlterField(
            model_name="stops",
            name="transit_agency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="views.transitagency",
            ),
        ),
        migrations.AlterField(
            model_name="stoptimes",
            name="transit_agency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="views.transitagency",
            ),
        ),
        migrations.AlterField(
            model_name="trips",
            name="transit_agency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="views.transitagency",
            ),
        ),
    ]
